export enum AppRoute {
  HOME = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  EMAIL_VERIFICATION = "/email-verification",
  PASSWORD_RESET = "/password-reset",
  PROFILE = "/profile",
  SEARCH = "/search",
  ADVANCED_SEARCH = "/search/advanced",
  LIBRARY = "/library",
  EXPLORE = "/explore",
  TRACK = "/track/:trackId",
  ALBUM = "/album/:albumId",
  PLAYLIST = "/playlist/:playlistId",
  SETTINGS = "/settings",
  NOT_FOUND = "/404",
}
