export enum AppRoute {
  HOME = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  EMAIL_VERIFICATION = "/email-verification",
  PASSWORD_RESET = "/password-reset",
  PROFILE = "/profile",
  PROFILE_EDIT = "/profile/edit",
  PROFILE_FOLLOWERS = "/profile/followers",
  PROFILE_FOLLOWINGS = "/profile/followings",
  PROFILE_PLAYLISTS = "/profile/playlists",
  SEARCH = "/search",
  SEARCH_BY_LYRICS = "/search/by-lyrics",
  SEARCH_BY_SOUND = "/search/by-sound",
  ADVANCED_SEARCH = "/search/advanced",
  LIBRARY = "/library",
  EXPLORE = "/explore",
  TRACK = "/track/:trackId",
  ALBUM = "/album/:albumId",
  PLAYLIST = "/playlist/:playlistId",
  PLAYLIST_EDIT = "/playlist/:playlistId/edit",
  SETTINGS = "/settings",
  NOT_FOUND = "/404",
}
